### PR TITLE
Fix redigo import

### PR DESCRIPTION
**Pull request by rsheasby**
The currently used redigo import is incorrect, as is uses an old, invalid redigo version. See here for citation: https://github.com/gomodule/redigo/issues/486#issuecomment-633237866

This PR fixes that, and tidies up all imports too

### CODE REVIEW

**Comment by rsheasby** [comment]
Also, it just occurred to me that there hasn't been a tag in a while. Probably worth adding a v0.2.0 tag if/when this gets merged.

**Comment by abraithwaite** [comment]
Nice, thanks!  I don't think I was targeting a particular version of redigo, so that should be fine.

I want to investigate why so much is being added to go.sum but afterwards I'll be happy to merge. ;-)

**Comment by rsheasby** [comment]
I figured out the source of all the extra sum lines. When I updated the dependencies, it updated msgp to the latest too, which now uses go modules (the previous version didn't have a go.mod/go.sum, so it wasn't actually imported as a module). Now that it is being imported as a module, its dependencies are integrity checked using the go.sum.

**Comment by abraithwaite** [comment]
Looks like go has some weird issues with resolving unecessary go.sum entries like these:

https://github.com/abraithwaite/jeff/pull/28/files#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63R20-R21

Even though these aren't referenced in the redigo `v1.8.5` tag.  I'm going to trust the compiler to not include these, even if they do somehow get downloaded.

Verified this happens for Go 1.15 and gotip, so 🤷🏽

**Comment by abraithwaite** [comment]
Going to merge and tag for you, but also going to hunt down what maybe causing those weird sum entries.

**Comment by abraithwaite** [comment]
Tracked it down to the `tinylib/msgp` lib actually, and created this:

https://github.com/tinylib/msgp/issues/293

Also watching this for `go mod why` improvements:

https://github.com/golang/go/issues/27900

**Pull request merged**
